"""HTTP and ingestion pacing settings."""

from __future__ import annotations

from travelcanary_pipeline.config._env import _env_bool, _env_int

HTTP_CONNECT_TIMEOUT_SECONDS = _env_int("HTTP_CONNECT_TIMEOUT_SECONDS", 10)
HTTP_READ_TIMEOUT_SECONDS = _env_int("HTTP_READ_TIMEOUT_SECONDS", 30)
HTTP_REQUEST_TIMEOUT = (HTTP_CONNECT_TIMEOUT_SECONDS, HTTP_READ_TIMEOUT_SECONDS)

GDELT_ROLLING_WINDOW_DAYS = _env_int("GDELT_ROLLING_WINDOW_DAYS", 120)

TRAVELCANARY_DAILY_SCHEDULE_ENABLED = _env_bool(
    "TRAVELCANARY_DAILY_SCHEDULE_ENABLED", False
)

UK_FCDO_DISCOVER_ALL_COUNTRIES = _env_bool("UK_FCDO_DISCOVER_ALL_COUNTRIES", True)

__all__ = [
    "GDELT_ROLLING_WINDOW_DAYS",
    "HTTP_CONNECT_TIMEOUT_SECONDS",
    "HTTP_READ_TIMEOUT_SECONDS",
    "HTTP_REQUEST_TIMEOUT",
    "TRAVELCANARY_DAILY_SCHEDULE_ENABLED",
    "UK_FCDO_DISCOVER_ALL_COUNTRIES",
]
