"""Validation-only public warehouse and orchestration contracts."""

from __future__ import annotations

TRAVEL_RISK_COLUMNS = [
    "destination_iso2",
    "destination_iso3",
    "destination_name",
    "issuing_government",
    "snapshot_date",
    "native_level",
    "native_level_label",
    "normalized_ordinal",
    "normalized_level_label",
    "normalization_status",
    "summary_text",
    "source_url",
    "source_published_at",
    "source_ingested_at",
]

PUBLIC_MART_COLUMNS = {
    "country_travel_risk": TRAVEL_RISK_COLUMNS,
    "country_travel_risk_history": TRAVEL_RISK_COLUMNS + ["snapshot_recorded_at"],
    "country_risk_signals": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "snapshot_date",
        "reporting_issuer_count",
        "normalized_ordinal_min",
        "normalized_ordinal_median",
        "normalized_ordinal_max",
        "normalized_ordinal_range",
        "latest_official_ingested_at",
        "gdelt_event_count_1d",
        "gdelt_material_conflict_events_1d",
        "gdelt_avg_goldstein_scale_1d",
        "gdelt_avg_tone_1d",
        "gdelt_event_count_7d",
        "gdelt_material_conflict_events_7d",
        "gdelt_material_conflict_share_7d",
        "gdelt_avg_goldstein_scale_7d",
        "gdelt_avg_tone_7d",
        "gdelt_latest_event_date",
        "gdelt_material_conflict_share_1d",
        "gdelt_is_fresh",
    ],
    "country_risk_overview": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "snapshot_date",
        "reporting_issuer_count",
        "reporting_issuers",
        "normalized_ordinal_min",
        "normalized_ordinal_median",
        "normalized_ordinal_max",
        "normalized_ordinal_range",
        "latest_official_ingested_at",
        "risk_direction",
        "disagreement_direction",
        "has_high_disagreement",
        "changed_issuer_count",
        "worsening_issuer_count",
        "improving_issuer_count",
        "matched_theme_count",
        "matched_themes",
        "context_alert_count",
        "context_alert_types",
        "has_warning_context_alert",
        "gdelt_event_count_1d",
        "gdelt_material_conflict_events_1d",
        "gdelt_material_conflict_share_1d",
        "gdelt_event_count_7d",
        "gdelt_material_conflict_events_7d",
        "gdelt_material_conflict_share_7d",
        "gdelt_latest_event_date",
        "gdelt_is_fresh",
        "required_source_count",
        "usable_required_source_count",
        "all_required_sources_usable",
        "gdelt_source_usable",
    ],
    "country_advisory_changes": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "issuing_government",
        "snapshot_date",
        "native_level",
        "native_level_label",
        "normalized_ordinal",
        "normalized_level_label",
        "previous_snapshot_date",
        "previous_normalized_ordinal",
        "normalized_ordinal_delta",
        "advisory_direction",
        "is_changed",
        "source_url",
        "source_published_at",
        "source_ingested_at",
    ],
    "country_risk_trends": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "snapshot_date",
        "reporting_issuer_count",
        "normalized_ordinal_min",
        "normalized_ordinal_median",
        "normalized_ordinal_max",
        "normalized_ordinal_range",
        "previous_snapshot_date",
        "previous_normalized_ordinal_median",
        "normalized_ordinal_median_delta",
        "risk_direction",
        "previous_normalized_ordinal_range",
        "normalized_ordinal_range_delta",
        "disagreement_direction",
        "has_high_disagreement",
        "latest_official_ingested_at",
    ],
    "country_advisory_themes": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "issuing_government",
        "snapshot_date",
        "theme",
        "matched_keyword_count",
        "matched_terms",
    ],
    "country_gdelt_event_types": [
        "event_date",
        "destination_iso3",
        "event_root_code",
        "event_root_label",
        "event_count",
        "mention_count",
        "material_conflict_events",
        "material_conflict_share",
        "avg_goldstein_scale",
        "avg_tone",
    ],
    "country_context_alerts": [
        "destination_iso2",
        "destination_iso3",
        "destination_name",
        "snapshot_date",
        "alert_type",
        "severity",
        "official_median_ordinal",
        "official_max_ordinal",
        "official_disagreement_range",
        "gdelt_latest_event_date",
        "gdelt_event_count_7d",
        "gdelt_material_conflict_events_7d",
        "gdelt_material_conflict_share_7d",
        "gdelt_mention_count_7d",
        "reason",
    ],
    "source_data_quality": [
        "source",
        "role",
        "health_status",
        "latest_status",
        "latest_finished_at",
        "hours_since_latest_run",
        "fetched_rows",
        "previous_accepted_rows",
        "relative_ratio",
        "canonical_ratio",
        "normalization_ratio",
        "message",
        "is_healthy",
        "is_usable",
        "freshness_status",
        "volume_status",
        "canonical_status",
        "normalization_status",
    ],
}

LIVE_PUBLIC_MARTS = (
    "country_travel_risk",
    "country_risk_signals",
    "country_risk_overview",
    "country_advisory_changes",
    "country_risk_trends",
    "country_advisory_themes",
    "country_gdelt_event_types",
    "country_context_alerts",
    "source_data_quality",
)

LIVE_NONEMPTY_PUBLIC_MARTS = (
    "country_travel_risk",
    "country_risk_signals",
    "country_risk_overview",
    "country_advisory_changes",
    "country_risk_trends",
    "country_gdelt_event_types",
    "source_data_quality",
)

PUBLIC_MARTS = tuple(PUBLIC_MART_COLUMNS)
LIVE_PUBLIC_MART_RELATIONS = tuple(
    f"travelcanary_marts.{mart}" for mart in LIVE_PUBLIC_MARTS
)
LIVE_NONEMPTY_PUBLIC_MART_RELATIONS = tuple(
    f"travelcanary_marts.{mart}" for mart in LIVE_NONEMPTY_PUBLIC_MARTS
)

PUBLIC_DAGSTER_JOBS = (
    "travelcanary_official_advisories_ingest",
    "travelcanary_gdelt_ingest",
    "travelcanary_dbt_build",
    "travelcanary_full_pipeline",
)

__all__ = [
    "LIVE_NONEMPTY_PUBLIC_MART_RELATIONS",
    "LIVE_NONEMPTY_PUBLIC_MARTS",
    "LIVE_PUBLIC_MART_RELATIONS",
    "LIVE_PUBLIC_MARTS",
    "PUBLIC_DAGSTER_JOBS",
    "PUBLIC_MART_COLUMNS",
    "PUBLIC_MARTS",
    "TRAVEL_RISK_COLUMNS",
]
